import CountyWeekTrend from './CountyWeekTrend.js';
import CityFlowResident from './CityFlowResident.js';
import CityFlowWorker from './CityFlowWorker.js';
import CityPopulationSource from './CityPopulationSource.js';
import CitySourceList from './CitySourceList.js';
import CityPopulation from './CityPopulation.js';
import CountyPopulation from './CountyPopulation.js';
import CountyTrend from './CountyTrend.js';
import CountyAgeStructure from './CountyAgeStructure.js';
import CountySexStructure from './CountySexStructure.js';
import CountyWork from './CountyWork.js';
import CountyLive from './CountyLive.js';
import CountyCommuting from './CountyCommuting.js';
import CityInfo from './CityInfo.js';
import CityTotalPopulation from './CityTotalPopulation.js';
import CountyTotalPopulation from './CountyTotalPopulation.js';
import CityResidentFlowInAndOut from './CityResidentFlowInAndOut.js';
import CityResidentFlowTotal from './CityResidentFlowTotal.js';
import CityResidentFlowIndex from './CityResidentFlowIndex.js';
import CityWorkerFlowInAndOut from './CityWorkerFlowInAndOut.js';
import CityWorkerFlowIndex from './CityWorkerFlowIndex.js';
import CityWorkerFlowTotal from './CityWorkerFlowTotal.js';
import CountySource from './CountySource.js';
import CountyStructure from './CountyStructure.js';
import CityStructureTrend from './CityStructureTrend.js';
import CountyFlowWorkLive from './CountyFlowWorkLive.js';
import CityCommuting from './CityCommuting.js';
import StreetCommuting from './StreetCommuting.js';
import StreetWork from './StreetWork.js';
import StreetLive from './StreetLive.js';
import StreetWorkHeat from './StreetWorkHeat.js';

export const countyWeekTrend = new CountyWeekTrend();
export const cityFlowResident = new CityFlowResident();
export const cityFlowWorker = new CityFlowWorker();
export const cityPopulationSource = new CityPopulationSource();
export const citySourceList = new CitySourceList();
export const cityPopulation = new CityPopulation();
export const countyPopulation = new CountyPopulation();
export const countyTrend = new CountyTrend();
export const countyAgeStructure = new CountyAgeStructure();
export const countySexStructure = new CountySexStructure();
export const countyWork = new CountyWork();
export const countyLive = new CountyLive();
export const countyCommuting = new CountyCommuting();
export const cityInfo = new CityInfo();
export const cityTotalPopulation = new CityTotalPopulation();
export const countyTotalPopulation = new CountyTotalPopulation();
export const cityResidentFlowInAndOut = new CityResidentFlowInAndOut();
export const cityResidentFlowTotal = new CityResidentFlowTotal();
export const cityResidentFlowIndex = new CityResidentFlowIndex();
export const cityWorkerFlowInAndOut = new CityWorkerFlowInAndOut();
export const cityWorkerFlowIndex = new CityWorkerFlowIndex();
export const cityWorkerFlowTotal = new CityWorkerFlowTotal();
export const countySource = new CountySource();
export const cityStructureTrend = new CityStructureTrend();
export const countyFlowWorkLive = new CountyFlowWorkLive();
export const countyStructure = new CountyStructure();
export const cityCommuting = new CityCommuting();
export const streetCommuting = new StreetCommuting();
export const streetWork = new StreetWork();
export const streetLive = new StreetLive();
export const streetWorkHeat =new StreetWorkHeat();